# 公共配置文件

spring:
  application:
    name: brainstorming-backend-question-service
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/brainstorming
    username: root
    password: 666
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  #    password: 666
  # nacos 配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # RabbitMQ 配置
  rabbitmq:
    host: 192.168.40.134
    port: 5672
    username: admin
    password: admin
    virtual-host: weiwei

server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /oj/question
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /oj   #修改cookie路径
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

#代码沙箱配置
codesandbox:
  type: remote
knife4j:
  enable: true
